# Generated by Django 5.2.16 on 2026-07-17 12:48

import utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_upload_status_lesson_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=utils.storages.CourseThumbnailStorage, upload_to='course_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, storage=utils.storages.SubmissionStorage, upload_to='payment_proofs/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.storages.DocumentStorage, upload_to='lesson_resources/'),
        ),
    ]
