# Generated by Django 5.2.16 on 2026-07-17 12:48

import utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_organizationsettings_min_password_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=utils.storages.ProfileImageStorage, upload_to='profile_pics/'),
        ),
    ]
