# Generated by Django 5.2.16 on 2026-07-17 12:48

import utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentattachment',
            name='file',
            field=models.FileField(storage=utils.storages.AssignmentStorage, upload_to='assignments/attachments/'),
        ),
        migrations.AlterField(
            model_name='submissionfile',
            name='file',
            field=models.FileField(storage=utils.storages.SubmissionStorage, upload_to='submissions/files/'),
        ),
    ]
